"""Human- and machine-readable map of the supported command surface."""


def describe():
    return {
        'read': [
            'what-if-course (bounded own published-assignment active submission hypotheses, including unsubmitted rows; fixed GraphQL metadata and native reset permission, no grades/comments/assessments; reported pagination is complete but hidden/historical storage remains unknown)',
            'what-if (exact own existing submission saved hypothetical point score via fixed GraphQL metadata; no official grade, answer, comment, read marker, assessment or submission initialization)',
            'feedback-comments (paginated published-comment effective-read indicators on the exact own submission, current/separately filtered all attempts; includes visible comments by all authors without identities/bodies, drafts/provisional grading/read-status include/assessment excluded; aggregate read can mask individual viewed-row storage)',
            'submission-attention (exact own existing submission aggregate read state and optional own annotation/rubric-feedback preference booleans; no feedback bodies, grade values, read-status include, assessment or explicit marker change)',
            'submission-comments (own-author native comments and drafts; paginated selected attempt or separately filtered all attempts, metadata/fingerprints by default and rendered-content opt-in; no peer/grader feedback, read markers or assessment initialization)',
            'draft (own next-attempt native submission draft only; metadata/fingerprints by default, rendered-content opt-in; no historical inventory, annotation/criteria initialization, final submission or quiz attempt)',
            'topic-languages (native preferred-language enum catalog, including deprecated values; schema acceptance only, no participant query, service access or translation generation)',
            'courses', 'doctor', 'find', 'me', 'profile', 'favorites', 'groups', 'group', 'course-groups',
            'course-users', 'group-users', 'group-membership',
            'permissions', 'group-categories', 'group-category', 'category-groups',
            'enrollments',
            'nicknames', 'nickname', 'colors', 'color',
            'settings', 'dashboard-positions',
            'channels',
            'activity', 'activity-summary',
            'inbox', 'conversation (no read-state change)', 'recipients',
            'todo', 'upcoming', 'calendar', 'event', 'appointment-groups', 'appointment-group', 'planner', 'planner-notes', 'planner-note',
            'appointment-team-reservations',
            'planner-overrides', 'planner-override', 'overview', 'deadlines', 'work', 'agenda', 'missing',
            'exports', 'export-status',
            'news', 'linked-files', 'assignments',
            'assignment-groups', 'assignment-group', 'submission', 'submissions', 'feedback', 'grades', 'peer-reviews',
            'syllabus', 'tabs', 'front-page', 'modules', 'module-items', 'outline', 'pages', 'page',
            'files', 'my-files', 'file-info', 'folders', 'my-folders', 'folder', 'folder-files', 'folder-folders',
            'file-quota',
            'sections', 'announcements', 'discussions', 'topic', 'thread', 'entries', 'entry', 'topic-ratings',
            'replies', 'quizzes (metadata only)', 'quiz (metadata only)',
            'new-quizzes (metadata only)', 'new-quiz (metadata only)',
            'rubrics', 'rubric', 'snapshot-diff (offline)',
            'snapshot-search (offline)', 'snapshot-agenda (offline cached dates only; current status/access unknown)',
        ],
        'read_with_native_side_effects': [
            'assignment (single-assignment REST GET can record assignment/module read access and asset analytics; use draft for own draft/policy inspection without that endpoint; no final submission or quiz attempt)',
            'topic-view (own effective display/shared defaults/locks; opt-in language/summary preferences and own pinned-unread indicator, not service access or reply read status; native GraphQL and participant-initialization acknowledgement, no peer replies; query can create own participant/default subscription/unread counters and planner cache)',
            'module-paths (own eligible mastery choices and assignment-ID projection; native module/conditional evaluation can have downstream effects, no path chosen or content/assessment navigation)',
            'module-sequence (native previous/next metadata, at most ten occurrences; no content navigation or mastery choice; conditional-release evaluation may have native effects)',
            'module-progress/module-item (metadata through paginated lists; native evaluation may materialize/recalculate progression, no explicit view/done events)',
            'page-revisions/page-revision (metadata by default; native page-read/edit-history permissions, exact numeric page IDs; GET can record module progress or repair legacy imported revision records)',
            'root-folder/my-root/folder-path (GET may materialize a missing native root folder)',
            'notification-preferences (GET may materialize default policy records)',
            'get (expert GET only; native server-side effects may apply)',
        ],
        'local_write': [
            'snapshot (private local file)',
            'sync (private local snapshot and change summary)',
            'snapshot-markdown (private local file, offline)',
            'download', 'download-linked (preview unless --yes)', 'export-download',
        ],
        'canvas_write': [
            'what-if-reset (ALL own course hypothetical scores, including hidden/historical rows and all own submission timestamps; explicit whole-course acknowledgement, identity/course/rights/reported-inventory-bound preview, one native bulk reset and separate reported-clear readback; optional whitelisted recalculated totals, hidden-row clearing unverified, no official grade/completion edit, fallback/retry/rollback)',
            'what-if-set/what-if-clear (one exact own existing submission hypothetical numeric/null score; native own/submit permission endpoint, identity/policy/attempt/current-score-bound preview and explicit forecast acknowledgement, native costly recalculation and separate saved-score readback; optional whitelisted hypothetical totals, not official grade edits or promised course results, no course-wide reset/retry/rollback)',
            'feedback-comment-mark-read (one exact visible published own-submission comment, not only own authored comments or every visible comment; identity/policy/attempt/paginated-indicator-bound preview and explicit acknowledgement, one native GraphQL mutation and separate effective-read readback; viewed-row storage masked by aggregate state and unverified, other observed changes not exclusively attributed, no content-view/completion proof, unread inverse, retry or rollback)',
            'submission-mark-read/submission-mark-unread (own aggregate/default-grade, grade/comment/rubric items and annotation/rubric-feedback preference surfaces kept distinct; account/assignment/existing-own-submission/indicator-bound preview and explicit acknowledgement, one native mutation and separate effective-state/preference readback; overall read can legitimately remain unread, individual participation storage and content viewing unverified, native visible-comment viewed rows/counters/planner effects, no completion/attempt/retry/rollback)',
            'comment-draft-create/comment-draft-edit/comment-draft-publish/comment-draft-delete (exact own existing submission and own authored drafts only; account/policy/current-content/paginated-inventory-bound preview and native effects acknowledgement, existing attachments/media on create, text-only edit; native group creation/publication/deletion/read-state/notification/caption/instructor grade-posting effects acknowledged but not independently verified, one mutation and own readback, no retry/rollback or published student comment edits)',
            'draft-save/draft-delete (own native GraphQL draft storage across six types, explicit current+1 attempt and account/assignment/current-rendered-state-bound preview; native submit rights stay endpoint-authoritative; one mutation and separate identity/attempt/representation readback, never final submission; deletion acknowledges ALL attempts with unknown historical inventory/absence; raw content storage, attachment normalization and submission criteria remain unverified; no retries, cleanup, upload or external launch)',
            'topic-view-set (own native sort/expansion/pinned-entry/language/summary preferences and separately acknowledged pinned-unread indicator; expansion inheritance and language clearing only, no null resets for non-null storage; schema catalog and account/context/state-bound preview, initialization acknowledgement and one GraphQL mutation; independent reported readback, hidden sort/expansion and cleared-language storage unverified; no content-read proof, translation/summary generation, peer reads, retry or rollback)',
            'topic-sections (native course discussion section filter, distinct from modern participant overrides; exact topic update, shared/audience acknowledgements, account/content/sections/inventory-bound preview, one PUT and independent exact-filter readback; old/new visibility remains endpoint-authoritative, no all-student visibility guarantee, roster/reply reads, retries or rollback)',
            'topic-todo (shared course/group ungraded discussion student to-do date or explicit clearing, not a private task or graded due date; exact topic update and native context-add permission for setting, shared/todo acknowledgements, account/content/audience/inventory-bound preview, one PUT and exact-instant independent readback; no planner/completion/availability guarantee, peer reads, retry or rollback)',
            'topic-duplicate (native ungraded prompt copy; dynamic creation rights, endpoint-authoritative instructor/admin/group eligibility, initial-post enforcement and shared/copy-effect acknowledgements; source/account/inventory-bound preview, one source POST, new-ID/own-author/independent readback and pinned-position map; replies/attachments/participant overrides are not a full backup, audience/publication/dates/order can change, no retry/cleanup)',
            'topic-schedule (ordinary course opening/closing instants or explicit clearing; shared-topic and availability-effect acknowledgements, native exact update permission, account/content/audience/time-zone/inventory-bound preview, one PUT with independent exact-instant readback; dates can publish drafts or reopen/close replies, course-midnight closing refused, no future-job guarantee/retry/rollback)',
            'topic-order (complete shared pinned-topic ordering; exact context read/moderation rights, all-pinned acknowledgement and account/inventory-bound preview, one native POST with exact order acknowledgement and independent paginated position readback; no text/pin/assignment changes, no retry/rollback)',
            'topic-configure (shared ungraded reply structure/likes/default views; exact update permission, additional initial-post visibility acknowledgement, account/content/audience/inventory-bound preview and exact option readback; native granular permission stripping is not hidden, no peer reads/retry/rollback)',
            'topic-publish/topic-unpublish/topic-close/topic-open/topic-pin/topic-unpin (ordinary ungraded shared states; native update/eligibility flags, closing-date/order acknowledgements, exact state and separate paginated inventory readback; observed collateral changes labeled, no retry/rollback)',
            'topic-create (shared ungraded discussion; dynamic native creation and moderation permissions, explicit publication preview, new-ID/own-author/exact-readback/inventory proof, no retry/cleanup)',
            'announcement-create/announcement-edit/announcement-delete/announcement-schedule/announcement-sections (native non-draft announcements; dynamic creation/exact update-delete rights, effect consent and account/content/inventory-bound preview; course dates/initial or edited section audiences and selected/preserved comment locks verified by independent readback; participant visibility/reply access, notifications, future jobs and recall unverified, no retry/cleanup/rollback)',
            'announcement-attachment-remove (exact readable announcement, native update plus attach rights, explicit shared/broadcast/file-removal consent and account/content/attachment/inventory-bound preview; one PUT and independent attachment-list clearing readback; native file soft deletion/related-record effects/storage erasure/other references/recall unverified, no file transfer/retry/cleanup/rollback)',
            'topic-podcast/announcement-podcast (shared native course feed/student-post modes and group enable-disable; exact update/moderation rights, effect consent and account/content/inventory-bound preview; stored flags and independent readback verified, feed URLs never printed/fetched; effective feed access, code revocation and delivery unverified)',
            'topic-attachment-set/announcement-attachment-set (native shared single-file multipart PUT, not file-ID association; exact update/attach rights, account/content/inventory/file-hash-bound preview and replacement consent; new attachment ID/size and independent topic readback verified, stored bytes/old-file deletion/storage/access/delivery unverified; no retry or cleanup)',
            'topic-edit/topic-delete (exact readable ungraded non-anonymous discussion prompts; native update/delete permission, shared/removal acknowledgement, account/content/audience/inventory-bound preview and independent readback; normalization and collateral fields labeled, linked assignment/root/child/announcement workflows excluded, no retry/rollback)',
            'module-path-select (own native mastery selection/switch; graded posted trigger and account/inventory/choice-bound preview, explicit assignment-change/switch acknowledgement; separate own choice readback, asynchronous/unverified outcomes labeled, availability/dates/downstream effects not asserted)',
            'module-item-done/module-item-not-done/module-item-mark-read (explicit own native progression events; student permission, account/full-item-inventory/policy-bound preview, matching digest and independent requirement readback; read requires prior-content-access acknowledgement, no assessment/score/submission simulation, planner/downstream effects not asserted)',
            'page-schedule (course RCE publication date/cancel; manager-only, enabled root-account feature, exact-ID revision/content/inventory-bound preview and independent stored-date/draft readback; front/linked-assignment pages refused, future background execution not asserted, no automatic publication/retry)',
            'page-duplicate (native course-only draft copy; separate creation/student-wiki authorization, exact source ID and revision/content/inventory-bound preview; explicit linked-assignment copy acknowledgement and independently verified exact lineage, unchanged source/front page; differences labeled, no automatic retry/publication/rollback)',
            'page-delete (native shared wiki soft deletion; separate delete permission, exact-ID revision/content/inventory-bound preview and digest, explicit linked-assignment cascade acknowledgement; independent inventory/ID/URL and linked-assignment readbacks, no front-page changes or automatic retry)',
            'page-restore (shared RCE title/body/URL; native full-update/history authorization, exact-ID account/revision/inventory-bound preview and digest, explicit front-page risk acknowledgement, separate page/revision/front readback; normalization is labeled, no automatic retry or repair)',
            'page-create/page-edit (shared RCE wiki content; explicit context/audience acknowledgement, native page-edit authorization, exact page IDs and revision-bound preview, matching digest and separate stored-page readback; native HTML normalization is labeled)',
            'channel-create/channel-delete (exact own contact methods; explicit message/removal acknowledgement, account/full-inventory-bound preview and matching digest; native confirmation, separate full own-inventory verification)',
            'profile-set (selected own name/profile/time-zone fields; shared-audience acknowledgement, account/profile-bound preview and matching digest; no SIS override, subsequent exact read-back verification)',
            'enrollment-accept/enrollment-reject (exact pending own Canvas invitation only; explicit membership acknowledgement, fresh account/invitation-bound preview and matching digest required; not official university registration)',
            'group-join/group-leave (own student-organized/community groups only; explicit native permission, account/group/current-membership-bound preview and matching digest required)',
            'favorite-add/favorite-remove/favorites-reset (own course/group favorites; account-bound preview, displayed-default warning and matching digest required)',
            'nickname-set/nickname-clear/nicknames-reset/color-set (own display preferences; account-bound preview and matching digest required, no shared course renaming)',
            'settings-set/dashboard-position-set/dashboard-order (selected own interface preferences only; account-bound preview and matching digest required)',
            'notification-preferences-set/notification-category-set (exact selected own-channel frequencies, category expands to currently reported keys only; account/channel/current-state-bound preview and matching digest required, partial-batch warning)',
            'activity-dismiss/activity-dismiss-all (hide own notifications only; account-bound preview, explicit all-item acknowledgement and matching digest required)',
            'event-create/event-edit/event-delete (personal calendar only; account-bound preview and matching digest required)',
            'appointment-reserve/appointment-cancel (exact own individual native Scheduler booking only; account/group/slot/current-state-bound preview and matching digest, no automatic cancellation/replacement, separate own-state read-back)',
            'appointment-team-reserve/appointment-team-cancel (one accepted own course team in the exact Scheduler group set; shared-team acknowledgement, account/membership/full-team-inventory-bound preview and matching digest, no booking replacement, separate participant and full-inventory read-back)',
            'task-create/task-edit/task-delete (personal planner notes; account-bound preview and matching digest required)',
            'planner-override-create/planner-override-edit/planner-override-delete (planner completion/dismissal; account-bound preview, explicit module-progress acknowledgement for course content)',
            'post (preview and matching digest required)',
            'entry-edit/entry-delete (own entry only; account-bound preview, matching digest and attachment-loss acknowledgement)',
            'entry-rate (own like only; visible target, enabled ratings, account-bound preview and matching digest required)',
            'topic-subscribe/topic-unsubscribe/topic-mark-read/topic-mark-unread/entry-mark-read/entry-mark-unread (only own subscription/read markers; account-bound preview and matching digest required)',
            'inbox-reply/inbox-compose (preview and matching digest required)',
            'inbox-edit/inbox-delete (own read/archive/star/subscription state or own-view removal; account-bound preview, matching digest and permanent-deletion acknowledgement)',
            'submit-url/submit-text/submit-file (preview and matching digest required)',
            'submission-comment (own submission only; account-bound preview and matching digest required)',
            'export-create (asynchronous course export; account-bound preview and matching digest required)',
            'my-file-edit/my-file-copy/my-file-delete/my-folder-create/my-folder-edit/my-folder-delete (personal file organization; account-bound preview, no overwrite, permanent acknowledgement for file deletion, empty folders only)',
            'upload-personal/upload-assignment-file/upload-context (account/file/folder-bound preview and matching digest required; course/group uploads are shared files, not submissions)',
        ],
        'auth': ['login', 'status', 'logout'],
        'format': 'JSON or human-readable brief index',
        'limitations': [
            'No quiz attempts', 'No OAuth browser consent yet',
            'Live uploads and submissions not yet validated',
        ],
    }
