"""Human- and machine-readable map of the supported command surface."""


def describe():
    return {
        'read': [
            'courses', 'doctor', 'find', 'me', 'profile', 'favorites', 'groups', 'group', 'course-groups',
            'course-users', 'group-users', 'group-membership',
            'permissions', 'group-categories', 'group-category', 'category-groups',
            'enrollments',
            'nicknames', 'nickname', 'colors', 'color',
            'settings', 'dashboard-positions',
            'channels',
            'activity', 'activity-summary',
            'inbox', 'conversation (no read-state change)', 'recipients',
            'todo', 'upcoming', 'calendar', 'event', 'planner', 'planner-notes', 'planner-note',
            'planner-overrides', 'planner-override', 'module-progress', 'overview', 'deadlines', 'work', 'agenda', 'missing',
            'exports', 'export-status',
            'news', 'linked-files', 'assignments', 'assignment',
            'assignment-groups', 'assignment-group', 'submission', 'submissions', 'feedback', 'grades', 'peer-reviews',
            'syllabus', 'tabs', 'front-page', 'modules', 'module-items', 'outline', 'pages', 'page',
            'files', 'my-files', 'file-info', 'folders', 'my-folders', 'folder', 'folder-files', 'folder-folders',
            'file-quota',
            'sections', 'announcements', 'discussions', 'topic', 'thread', 'entries', 'entry', 'topic-ratings',
            'replies', 'quizzes (metadata only)', 'quiz (metadata only)',
            'new-quizzes (metadata only)', 'new-quiz (metadata only)',
            'rubrics', 'rubric', 'snapshot-diff (offline)',
            'snapshot-search (offline)',
        ],
        'read_with_native_side_effects': [
            'root-folder/my-root/folder-path (GET may materialize a missing native root folder)',
            'notification-preferences (GET may materialize default policy records)',
            'get (expert GET only; native server-side effects may apply)',
        ],
        'local_write': [
            'snapshot (private local file)',
            'sync (private local snapshot and change summary)',
            'snapshot-markdown (private local file, offline)',
            'download', 'download-linked (preview unless --yes)', 'export-download',
        ],
        'canvas_write': [
            'profile-set (selected own name/profile/time-zone fields; shared-audience acknowledgement, account/profile-bound preview and matching digest; no SIS override, subsequent exact read-back verification)',
            'enrollment-accept/enrollment-reject (exact pending own Canvas invitation only; explicit membership acknowledgement, fresh account/invitation-bound preview and matching digest required; not official university registration)',
            'group-join/group-leave (own student-organized/community groups only; explicit native permission, account/group/current-membership-bound preview and matching digest required)',
            'favorite-add/favorite-remove/favorites-reset (own course/group favorites; account-bound preview, displayed-default warning and matching digest required)',
            'nickname-set/nickname-clear/nicknames-reset/color-set (own display preferences; account-bound preview and matching digest required, no shared course renaming)',
            'settings-set/dashboard-position-set/dashboard-order (selected own interface preferences only; account-bound preview and matching digest required)',
            'notification-preferences-set (exact selected own-channel frequencies; account/channel/current-state-bound preview and matching digest required, partial-batch warning)',
            'activity-dismiss/activity-dismiss-all (hide own notifications only; account-bound preview, explicit all-item acknowledgement and matching digest required)',
            'event-create/event-edit/event-delete (personal calendar only; account-bound preview and matching digest required)',
            'task-create/task-edit/task-delete (personal planner notes; account-bound preview and matching digest required)',
            'planner-override-create/planner-override-edit/planner-override-delete (planner completion/dismissal; account-bound preview, explicit module-progress acknowledgement for course content)',
            'post (preview and matching digest required)',
            'entry-edit/entry-delete (own entry only; account-bound preview, matching digest and attachment-loss acknowledgement)',
            'entry-rate (own like only; visible target, enabled ratings, account-bound preview and matching digest required)',
            'topic-subscribe/topic-unsubscribe/topic-mark-read/topic-mark-unread/entry-mark-read/entry-mark-unread (only own subscription/read markers; account-bound preview and matching digest required)',
            'inbox-reply/inbox-compose (preview and matching digest required)',
            'inbox-edit/inbox-delete (own read/archive/star/subscription state or own-view removal; account-bound preview, matching digest and permanent-deletion acknowledgement)',
            'submit-url/submit-text/submit-file (preview and matching digest required)',
            'submission-comment (own submission only; account-bound preview and matching digest required)',
            'export-create (asynchronous course export; account-bound preview and matching digest required)',
            'my-file-edit/my-file-copy/my-file-delete/my-folder-create/my-folder-edit/my-folder-delete (personal file organization; account-bound preview, no overwrite, permanent acknowledgement for file deletion, empty folders only)',
            'upload-personal/upload-assignment-file/upload-context (account/file/folder-bound preview and matching digest required; course/group uploads are shared files, not submissions)',
        ],
        'auth': ['login', 'status', 'logout'],
        'format': 'JSON or human-readable brief index',
        'limitations': [
            'No quiz attempts', 'No OAuth browser consent yet',
            'Live uploads and submissions not yet validated',
        ],
    }
